---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age146mfz0d2ezk9mqwh3tmqnhjypdvhxeecampxh7elkauk4fus0fns02d3gh"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age146mfz0d2ezk9mqwh3tmqnhjypdvhxeecampxh7elkauk4fus0fns02d3gh"
