apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:u94rl3ZwTgHRP/7l9TN6GYrEtDKx37GI,iv:7h4El46WTaHsQbLYjI/SxCYSwXCL28cdPvpSYj2LDe4=,tag:XPRguQcjNyu+Mqb5Ra+Aqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146mfz0d2ezk9mqwh3tmqnhjypdvhxeecampxh7elkauk4fus0fns02d3gh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dDFIN0ZNSDhOYmJuTC9z
            RERETkJtcHdhN0tQaUpKSGJxeDh1akVRM2pzClVwbTVqY0lvL1YxQUxYNFhuaTFZ
            ZC9BeitFMzd0TkdYeU5ZSzFidG9pU2MKLS0tIDRTSXBSWFJmZ2dVUlkzSlJBb3NU
            VU9HVFh5aGpiM0NnU0laeEJNS04xeGcK1g19CMoCD0iy+/mZTQQVTva087Ojy6X7
            MLBE4bVcBZGuPP3QJuSipJRyT1fSDUy7IMPGHY2wVgPhkgaEWVDx5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T04:25:39Z"
    mac: ENC[AES256_GCM,data:GHt9NGwss0G1PvrSKKhx28EnjEaVdEmzEv6dkGEmICxd8D38Q7sJFBYFWZDlNFVXW16lKz7h0HiwtX2kGZqyKq2oTbrGHEtKvSBRACglAgrxQbS9ekmeveJe8kHUNAoujrSsmMtaXjBnnankd7HTZ3VDRQGbn+tIc073vkrFGUM=,iv:S9Tka35zrbCXS6a5fX5xUghlrb8q7gkVT3LNdM/X6AQ=,tag:JVplmaUxXMetzhYJeLkwEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
